# Site settings
title: Zwickypedia
header-img: img/jenny_lake_pano.JPG
email: andrew.zwicky@gmail.com
copyright_name: Andrew V. Zwicky
description: ""
baseurl: ""
url: "http://andrewzwicky.github.io/"
twitter_username: andrewzwicky
github_username:  andrewzwicky
facebook_username:  andrew.v.zwicky
email_username:  andrew.zwicky@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

excerpt_separator: <!--break-->

gems: [jekyll-paginate, jekyll-feed]
